# Generated by Django 2.0.6 on 2018-06-14 20:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('street_address', models.CharField(blank=True, max_length=50, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='City')),
                ('details', models.CharField(blank=True, max_length=300, verbose_name='Details')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_when', models.DateField(default=django.utils.timezone.now, verbose_name='Ordered When')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Order Total')),
                ('order_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_on_store', models.BooleanField(default=True, verbose_name='Display product on store')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Product Picture')),
                ('brand', models.CharField(choices=[('CATANDJACK', 'Cat and Jack'), ('CARTERS', 'Carters'), ('OSHKOSH', 'Oshkosh'), ('OSHKOSHG', 'Oshkosh Genuino'), ('CENTRUM', 'Centrum'), ('COLICCALM', 'Colic Calm'), ('DESISTIN', 'Desistin'), ('DISNEY', 'Disney'), ('GAP', 'GAP'), ('KIRKLAND', 'Kirkland'), ('NATROL', 'Natrol'), ('NATURESBOUNTY', 'Natures Bounty'), ('OTHERS', 'Others')], default='CATANDJACK', max_length=15)),
                ('genre', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_when', models.DateField(default=django.utils.timezone.now, verbose_name='Sold when')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sale Total')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_on', models.DateField(default=django.utils.timezone.now, verbose_name='Shopping on')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolar_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Dolar Price')),
                ('dolar_quotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Dolar Quotation')),
                ('real_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Real Price')),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sales Price')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('size', models.CharField(choices=[('NB', 'New Born'), ('03M', '0-3 Months'), ('06M', '3-6 Months'), ('09M', '6-9 Months'), ('12M', '9-12 Months'), ('18M', '18 Months'), ('02T', '2 Years'), ('03T', '3 Years'), ('04T', '4 Years'), ('05T', '5 Years'), ('06T', '6 Years'), ('07T', '7 Years'), ('08T', '8 Years'), ('UNQ', 'Unique')], default='NB', max_length=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Store')),
            ],
        ),
        migrations.AddField(
            model_name='shopping',
            name='shopping_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.ShoppingProduct'),
        ),
        migrations.AddField(
            model_name='shopping',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Store'),
        ),
        migrations.AddField(
            model_name='sale',
            name='shopping_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.ShoppingProduct'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='shopping_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.ShoppingProduct'),
        ),
    ]
