# Generated by Django 2.0.6 on 2018-06-14 22:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_display_on_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='shopping_product',
        ),
        migrations.AddField(
            model_name='shoppingproduct',
            name='shopping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.Shopping'),
            preserve_default=False,
        ),
    ]
