# Generated by Django 2.0.6 on 2018-06-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20180614_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingproduct',
            name='dolar_quotation',
        ),
        migrations.AddField(
            model_name='shopping',
            name='dolar_quotation',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Dolar Quotation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoppingproduct',
            name='dolar_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Dolar Price'),
        ),
        migrations.AlterField(
            model_name='shoppingproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='shoppingproduct',
            name='real_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Real Price'),
        ),
        migrations.AlterField(
            model_name='shoppingproduct',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sales Price'),
        ),
    ]
