# Generated by Django 2.0.6 on 2018-06-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_shoppingproduct_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingproduct',
            name='real_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Real Price'),
            preserve_default=False,
        ),
    ]
