# Generated by Django 2.0.6 on 2018-06-14 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shoppingproduct_real_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingproduct',
            name='shopping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shopping'),
        ),
    ]
