# Generated by Django 2.0.5 on 2018-06-15 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20180614_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='shopping_product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sold_to',
        ),
        migrations.RemoveField(
            model_name='shoppingproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingproduct',
            name='shopping',
        ),
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], default='F', max_length=2),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='ShoppingProduct',
        ),
    ]
