# Generated by Django 2.0.5 on 2018-06-15 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20180615_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolar_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Dolar Price')),
                ('real_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Real Price')),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sales Price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('size', models.CharField(choices=[('NB', 'New Born'), ('03M', '0-3 Months'), ('06M', '3-6 Months'), ('09M', '6-9 Months'), ('12M', '9-12 Months'), ('18M', '18 Months'), ('02T', '2 Years'), ('03T', '3 Years'), ('04T', '4 Years'), ('05T', '5 Years'), ('06T', '6 Years'), ('07T', '7 Years'), ('08T', '8 Years'), ('UNQ', 'Unique')], default='NB', max_length=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.Product')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shopping')),
            ],
        ),
    ]
