# Generated by Django 2.0.5 on 2018-06-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_shoppingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_sold',
            field=models.BooleanField(default=False, verbose_name='Sold?'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Order Item Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Unit Price'),
            preserve_default=False,
        ),
    ]
