# Generated by Django 2.0.5 on 2018-06-15 03:23

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20180615_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sold_when',
            field=models.DateField(blank=True, default=timezone.now, verbose_name='Sold When'),
            preserve_default=False,
        ),
    ]
