# Generated by Django 2.0.5 on 2018-06-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_order_sold_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sold_when',
            field=models.DateField(blank=True, null=True, verbose_name='Sold When'),
        ),
    ]
