# Generated by Django 2.0.5 on 2018-06-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20180615_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivered',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='delivered_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
    ]
