# Generated by Django 2.0.5 on 2018-06-12 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='created_by',
        ),
    ]
