# Generated by Django 2.0.5 on 2018-06-13 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_choice_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('photo', models.BinaryField(blank=True)),
                ('dolarprice', models.FloatField()),
                ('realprice', models.FloatField()),
            ],
        ),
    ]
