# Generated by Django 2.0.5 on 2018-06-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dolarprice',
            field=models.FloatField(verbose_name='Dolar Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='realprice',
            field=models.FloatField(verbose_name='Real Price'),
        ),
    ]
