# Generated by Django 2.0.5 on 2018-06-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180613_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Product Picture'),
        ),
    ]
