# Generated by Django 2.0.6 on 2018-06-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20180613_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('CATANDJACK', 'Cat and Jack'), ('CARTERS', 'Carters'), ('OSHKOSH', 'Oshkosh'), ('OSHKOSHG', 'Oshkosh Genuino'), ('CENTRUM', 'Centrum'), ('COLICCALM', 'Colic Calm'), ('DESISTIN', 'Desistin'), ('DISNEY', 'Disney'), ('GAP', 'GAP'), ('KIRKLAND', 'Kirkland'), ('NATROL', 'Natrol'), ('NATURESBOUNTY', 'Natures Bounty'), ('OTHERS', 'Others')], default='CATANDJACK', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=2),
        ),
    ]
