# Generated by Django 2.0.6 on 2018-06-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180613_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_on_store',
            field=models.BooleanField(default=True, verbose_name='Display product on store'),
            preserve_default=False,
        ),
    ]
