# Generated by Django 2.0.5 on 2018-06-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_product_display_on_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dolarprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='realprice',
        ),
        migrations.AddField(
            model_name='product',
            name='dolar_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Dolar Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='real_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Real Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='sales_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sales Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_on_store',
            field=models.BooleanField(default=True, verbose_name='Display product on store'),
        ),
    ]
