# Generated by Django 2.0.5 on 2018-06-14 01:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180614_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('street_address', models.CharField(max_length=50, verbose_name='Street')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('details', models.CharField(max_length=300, verbose_name='Details')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_when', models.DateTimeField(default=datetime.datetime(2018, 6, 14, 1, 0, 49, 536297, tzinfo=utc), verbose_name='Ordered When')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Order Total')),
                ('order_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_when', models.DateTimeField(default=datetime.datetime(2018, 6, 14, 1, 0, 49, 535773, tzinfo=utc), verbose_name='Sold when')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sale Total')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopping_on', models.DateTimeField(default=datetime.datetime(2018, 6, 14, 1, 0, 49, 534900, tzinfo=utc), verbose_name='Shopping on')),
                ('dolar_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Dolar Price')),
                ('dolar_quotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Dolar Quotation')),
                ('real_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Real Price')),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sales Price')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('size', models.CharField(choices=[('NB', 'New Born'), ('03M', '0-3 Months'), ('06M', '3-6 Months'), ('09M', '6-9 Months'), ('12M', '9-12 Months'), ('18M', '18 Months'), ('02T', '2 Years'), ('03T', '3 Years'), ('04T', '4 Years'), ('05T', '5 Years'), ('06T', '6 Years'), ('07T', '7 Years'), ('08T', '8 Years'), ('UNQ', 'Unique')], default='NB', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Store')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='dolarprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='realprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sales_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='shopping',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Store'),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sold_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Product'),
        ),
    ]
