# Generated by Django 2.0.5 on 2018-06-14 01:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180614_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='details',
            field=models.CharField(blank=True, max_length=300, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='street_address',
            field=models.CharField(blank=True, max_length=50, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_when',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 1, 2, 5, 391249, tzinfo=utc), verbose_name='Ordered When'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_when',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 1, 2, 5, 390714, tzinfo=utc), verbose_name='Sold when'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='shopping_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 14, 1, 2, 5, 389790, tzinfo=utc), verbose_name='Shopping on'),
        ),
    ]
