# Generated by Django 2.0.5 on 2018-06-14 01:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20180614_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dolar_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Dolar Price')),
                ('dolar_quotation', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Dolar Quotation')),
                ('real_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Real Price')),
                ('sales_price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Sales Price')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('size', models.CharField(choices=[('NB', 'New Born'), ('03M', '0-3 Months'), ('06M', '3-6 Months'), ('09M', '6-9 Months'), ('12M', '9-12 Months'), ('18M', '18 Months'), ('02T', '2 Years'), ('03T', '3 Years'), ('04T', '4 Years'), ('05T', '5 Years'), ('06T', '6 Years'), ('07T', '7 Years'), ('08T', '8 Years'), ('UNQ', 'Unique')], default='NB', max_length=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='dolar_price',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='dolar_quotation',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='real_price',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='sales_price',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='size',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_when',
            field=models.DateField(default=datetime.datetime(2018, 6, 14, 1, 9, 56, 676680, tzinfo=utc), verbose_name='Ordered When'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sold_when',
            field=models.DateField(default=datetime.datetime(2018, 6, 14, 1, 9, 56, 676220, tzinfo=utc), verbose_name='Sold when'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='shopping_on',
            field=models.DateField(default=datetime.datetime(2018, 6, 14, 1, 9, 56, 675366, tzinfo=utc), verbose_name='Shopping on'),
        ),
        migrations.AddField(
            model_name='order',
            name='shopping_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='polls.ShoppingProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='shopping_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='polls.ShoppingProduct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopping',
            name='shopping_product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='polls.ShoppingProduct'),
            preserve_default=False,
        ),
    ]
