# Generated by Django 2.0.6 on 2018-06-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20180614_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_to',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shopping_product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='shopping_product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='sold_to',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='shopping_product',
        ),
        migrations.RemoveField(
            model_name='shopping',
            name='store',
        ),
        migrations.RemoveField(
            model_name='shoppingproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Shopping',
        ),
        migrations.DeleteModel(
            name='ShoppingProduct',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
